### ISSUE TITLE
Steering and throttle missing in bag file?

### ISSUE THREAD

**Issue by Kishwar** [project-omicron/DeepBerlinDataset#1]
Hello Kurbakov,

Thanks for sharing the file. I have download and read the .bag file. There are just images inside. File doesn't show any info related to steering and throttle. Do I miss something?

Thanks and best regards,
Kishwar Kumar

**Comment by kurbakov** [comment]
Hi, Kishwar! Thanks a lot for the report. I will check it tomorrow and write you back!

**Comment by kurbakov** [comment]
Yes, I checked the rosbag and can confirm that it has only images. Sorry for that. Something went wrong during the recording. We will investigate it, but unfortunately can not provide the new data set for now.
